CREATE DATABASE IF NOT EXISTS userapi;
CREATE DATABASE IF NOT EXISTS productapi;
CREATE DATABASE IF NOT EXISTS orderapi;
CREATE DATABASE IF NOT EXISTS inventoryapi;
CREATE DATABASE IF NOT EXISTS paymentapi;